/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jfrmcalculadora;

/**
 *
 * @author cpcar
 */
public class jfrmCalcu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jfrmCalcu.class.getName());

    /**
     * Creates new form jfrmCalcu
     */
    private String entrada="";
    private double numero1, numero2;
    private String operador;
    public jfrmCalcu() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jbtnPunto1 = new javax.swing.JButton();
        jtxtCantidad = new javax.swing.JTextField();
        jbtnNum7 = new javax.swing.JButton();
        jbtnNum8 = new javax.swing.JButton();
        jbtnNum9 = new javax.swing.JButton();
        jbtnNum4 = new javax.swing.JButton();
        jbtnNum5 = new javax.swing.JButton();
        jbtnNum6 = new javax.swing.JButton();
        jbtnNum1 = new javax.swing.JButton();
        jbtnNum2 = new javax.swing.JButton();
        jbtnNum3 = new javax.swing.JButton();
        jbtnDivi = new javax.swing.JButton();
        jbtnMulti = new javax.swing.JButton();
        jbtnResta = new javax.swing.JButton();
        jbtnNum0 = new javax.swing.JButton();
        jbtnAC = new javax.swing.JButton();
        jbtnIgual = new javax.swing.JButton();
        jbtnSuma = new javax.swing.JButton();
        jbtnPunto = new javax.swing.JButton();
        jbtnraiz = new javax.swing.JButton();
        jbtnraiz1 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        jbtnPunto1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnPunto1.setText(".");
        jbtnPunto1.addActionListener(this::jbtnPunto1ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtnNum7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnNum7.setText("7");
        jbtnNum7.addActionListener(this::jbtnNum7ActionPerformed);

        jbtnNum8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnNum8.setText("8");
        jbtnNum8.addActionListener(this::jbtnNum8ActionPerformed);

        jbtnNum9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnNum9.setText("9");
        jbtnNum9.addActionListener(this::jbtnNum9ActionPerformed);

        jbtnNum4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnNum4.setText("4");
        jbtnNum4.addActionListener(this::jbtnNum4ActionPerformed);

        jbtnNum5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnNum5.setText("5");
        jbtnNum5.addActionListener(this::jbtnNum5ActionPerformed);

        jbtnNum6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnNum6.setText("6");
        jbtnNum6.addActionListener(this::jbtnNum6ActionPerformed);

        jbtnNum1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnNum1.setText("1");
        jbtnNum1.addActionListener(this::jbtnNum1ActionPerformed);

        jbtnNum2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnNum2.setText("2");
        jbtnNum2.addActionListener(this::jbtnNum2ActionPerformed);

        jbtnNum3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnNum3.setText("3");
        jbtnNum3.addActionListener(this::jbtnNum3ActionPerformed);

        jbtnDivi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnDivi.setText("/");
        jbtnDivi.addActionListener(this::jbtnDiviActionPerformed);

        jbtnMulti.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnMulti.setText("*");
        jbtnMulti.addActionListener(this::jbtnMultiActionPerformed);

        jbtnResta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnResta.setText("-");
        jbtnResta.addActionListener(this::jbtnRestaActionPerformed);

        jbtnNum0.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnNum0.setText("0");
        jbtnNum0.addActionListener(this::jbtnNum0ActionPerformed);

        jbtnAC.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnAC.setText("ac");
        jbtnAC.addActionListener(this::jbtnACActionPerformed);

        jbtnIgual.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnIgual.setText("=");
        jbtnIgual.addActionListener(this::jbtnIgualActionPerformed);

        jbtnSuma.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnSuma.setText("+");
        jbtnSuma.addActionListener(this::jbtnSumaActionPerformed);

        jbtnPunto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnPunto.setText(".");
        jbtnPunto.addActionListener(this::jbtnPuntoActionPerformed);

        jbtnraiz.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnraiz.setText("√ ");
        jbtnraiz.addActionListener(this::jbtnraizActionPerformed);

        jbtnraiz1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnraiz1.setText("%");
        jbtnraiz1.addActionListener(this::jbtnraiz1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnNum7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnNum8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnNum9))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jbtnDivi, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jbtnNum1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtnNum2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtnNum3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtnResta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jbtnNum4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtnNum5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtnNum6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jtxtCantidad))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnNum0)
                                .addGap(12, 12, 12)
                                .addComponent(jbtnSuma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnIgual)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnPunto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnraiz)
                                .addGap(3, 3, 3)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnAC, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jbtnraiz1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNum7)
                    .addComponent(jbtnNum8)
                    .addComponent(jbtnNum9)
                    .addComponent(jbtnDivi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNum4)
                    .addComponent(jbtnNum5)
                    .addComponent(jbtnNum6)
                    .addComponent(jbtnMulti))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNum1)
                    .addComponent(jbtnNum2)
                    .addComponent(jbtnNum3)
                    .addComponent(jbtnResta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNum0)
                    .addComponent(jbtnSuma)
                    .addComponent(jbtnAC)
                    .addComponent(jbtnIgual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnPunto)
                    .addComponent(jbtnraiz)
                    .addComponent(jbtnraiz1))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnACActionPerformed
        entrada="0";
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnACActionPerformed

    private void jbtnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIgualActionPerformed
        double resultado;
        numero2=Double.parseDouble(entrada);
        jtxtCantidad.setText("");
        entrada="";
        
        if (operador.equals("+")){
            resultado=numero1+numero2;
            entrada=String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
        }
            if (operador.equals("*")){
            resultado=numero1*numero2;
            entrada=String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
            }
            if (operador.equals("-")){
            resultado=numero1-numero2;
            entrada=String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
            }
            if (operador.equals("/")){
            resultado=numero1/numero2;
            entrada=String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
        }
    }//GEN-LAST:event_jbtnIgualActionPerformed

    private void jbtnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSumaActionPerformed
        numero1=Double.parseDouble(entrada);
        entrada="";
        operador="+";
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnSumaActionPerformed

    private void jbtnNum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum7ActionPerformed
        entrada=entrada +7;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnNum7ActionPerformed

    private void jbtnNum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum8ActionPerformed
        entrada=entrada +8;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnNum8ActionPerformed

    private void jbtnNum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum9ActionPerformed
        entrada=entrada +9;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnNum9ActionPerformed

    private void jbtnNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum4ActionPerformed
        entrada=entrada +4;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnNum4ActionPerformed

    private void jbtnNum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum5ActionPerformed
        entrada=entrada +5;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnNum5ActionPerformed

    private void jbtnNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum6ActionPerformed
        entrada=entrada +6;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnNum6ActionPerformed

    private void jbtnNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum1ActionPerformed
        entrada=entrada +1;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnNum1ActionPerformed

    private void jbtnNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum2ActionPerformed
        entrada=entrada +2;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnNum2ActionPerformed

    private void jbtnNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum3ActionPerformed
        entrada=entrada +3;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnNum3ActionPerformed

    private void jbtnNum0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNum0ActionPerformed
        entrada=entrada +0;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnNum0ActionPerformed

    private void jbtnDiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDiviActionPerformed
        numero1=Double.parseDouble(entrada);
        entrada="";
        operador="/";
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnDiviActionPerformed

    private void jbtnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMultiActionPerformed
        numero1=Double.parseDouble(entrada);
        entrada="";
        operador="*";
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnMultiActionPerformed

    private void jbtnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRestaActionPerformed
        numero1=Double.parseDouble(entrada);
        entrada="";
        operador="-";
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnRestaActionPerformed

    private void jbtnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPuntoActionPerformed
      if(!entrada.contains(".")){
          if(entrada.equals("")){
              entrada="0.";
          }else {
              entrada = entrada +".";
          }
          jtxtCantidad.setText(entrada);
      }
    }//GEN-LAST:event_jbtnPuntoActionPerformed

    private void jbtnPunto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPunto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPunto1ActionPerformed

    private void jbtnraizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnraizActionPerformed
        double valor = Double.parseDouble(entrada);
        
        if (valor >=0) {
            valor = Math.sqrt(valor);
            entrada = String.valueOf(valor);
        }else{
            entrada ="error";
        }
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnraizActionPerformed

    private void jbtnraiz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnraiz1ActionPerformed
        double valor = Double.parseDouble(entrada);
        valor = valor / 100;
        entrada = String.valueOf(valor);
        jtxtCantidad.setText(entrada);
               
    }//GEN-LAST:event_jbtnraiz1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jfrmCalcu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbtnAC;
    private javax.swing.JButton jbtnDivi;
    private javax.swing.JButton jbtnIgual;
    private javax.swing.JButton jbtnMulti;
    private javax.swing.JButton jbtnNum0;
    private javax.swing.JButton jbtnNum1;
    private javax.swing.JButton jbtnNum2;
    private javax.swing.JButton jbtnNum3;
    private javax.swing.JButton jbtnNum4;
    private javax.swing.JButton jbtnNum5;
    private javax.swing.JButton jbtnNum6;
    private javax.swing.JButton jbtnNum7;
    private javax.swing.JButton jbtnNum8;
    private javax.swing.JButton jbtnNum9;
    private javax.swing.JButton jbtnPunto;
    private javax.swing.JButton jbtnPunto1;
    private javax.swing.JButton jbtnResta;
    private javax.swing.JButton jbtnSuma;
    private javax.swing.JButton jbtnraiz;
    private javax.swing.JButton jbtnraiz1;
    private javax.swing.JTextField jtxtCantidad;
    // End of variables declaration//GEN-END:variables
}
